package gr.hua.DistSysApp.ritoAPI.Controllers.UserControllers;

import gr.hua.DistSysApp.ritoAPI.Models.Entities.User;
import gr.hua.DistSysApp.ritoAPI.Repositories.UserRepository;
import gr.hua.DistSysApp.ritoAPI.Services.AdminService;
import gr.hua.DistSysApp.ritoAPI.Services.PremiumUserServiceException;
import gr.hua.DistSysApp.ritoAPI.Services.UserService;
import gr.hua.DistSysApp.ritoAPI.exceptionHandling.ResourceNotFoundException;
import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.Optional;

@RestController
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private UserService userService;


    @GetMapping("/user")
    public String user(){
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        String username = authentication.getName();
        return "Hello, " + username + " you have: " + authentication.getAuthorities() + " authorities";
    }

    @GetMapping(path="/user/requestMatchHistory")
    public String requestMatchHistory () throws JSONException, PremiumUserServiceException, ResourceNotFoundException {
        try{
            JSONObject response = userService.requestMatchHistory();
            if (response==null) throw new ResourceNotFoundException("Error while making the request");
            return response.toString();
        }catch (PremiumUserServiceException e){
            throw new PremiumUserServiceException("Internal Server Exception while getting exception");
        }
    }

    @GetMapping(path="/user/showMatchHistory")
    @ResponseBody
    public String getMatchHistory (@RequestParam int requestId) throws JSONException, PremiumUserServiceException, ResourceNotFoundException {
        try{
            JSONObject response = userService.showRequestResults(requestId);
            if (response==null) throw new ResourceNotFoundException("Match History Data not found");
            return response.toString();
        }catch (PremiumUserServiceException e){
            throw new PremiumUserServiceException("Internal Server Exception while getting exception");
        }
    }

    @GetMapping(path="/user/requestLeaderboards")
    public String requestLeaderboards () throws JSONException, PremiumUserServiceException, ResourceNotFoundException {
        try{
            JSONObject response = userService.requestLeaderboards();
            if (response==null) throw new ResourceNotFoundException("Error while making the request");
            return response.toString();
        }catch (PremiumUserServiceException e){
            throw new PremiumUserServiceException("Internal Server Exception while getting exception");
        }
    }

    @GetMapping(path="/user/requestMyProfile")
    public String requestMyProfile () throws JSONException, PremiumUserServiceException, ResourceNotFoundException {
        try{
            JSONObject response = userService.requestMyProfile();
            if (response==null) throw new ResourceNotFoundException("Error while making the request");
            return response.toString();
        }catch (PremiumUserServiceException e){
            throw new PremiumUserServiceException("Internal Server Exception while getting exception");
        }
    }

    @GetMapping(path="/user/requestChampionStatistics")
    public String requestChampionStats () throws JSONException, PremiumUserServiceException, ResourceNotFoundException {
        try{
            JSONObject response = userService.requestChampionStats();
            if (response==null) throw new ResourceNotFoundException("Error while making the request");
            return response.toString();
        }catch (PremiumUserServiceException e){
            throw new PremiumUserServiceException("Internal Server Exception while getting exception");
        }
    }


}